version: '3.9'

services:
  spring-boot:
    build:
      context: .                 
      dockerfile: Dockerfile
      target: prod                
    ports:
      - "9000:9000"              
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped   